name: deploy

on:
  push:
    branches: [main]

jobs: 
  deploy:
    name: deploy to datalake
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: set up python 3.8
        uses: actions/steup-python@v2
        with:
          python-version: 3.8

      - name: harshicorp - setup terraform
        uses: harshicorp/setup-terraform@v1.2.1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: iac apply
        env:
          COMMAND_IAC: terraform
        run:
          cd "module 1 - Fundamentals of Data Architecture and Cloud Solutions/classes/iac"
          $COMMAND_IAC init
          $COMMAND_IAC fmt
          $COMMAND_IAC validate
          $COMMAND_IAC plan
          $COMMAND_IAC apply -auto-approve